# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`

input {
  kb_layout = jp

  follow_mouse = 2
}

# monitor management
exec = ~/.config/hypr/custom/scripts/monitor-watch.sh

# cursor settings
cursor {
  enable_hyprcursor = false
}
exec = hyprctl setcursor PlanaCursor 72
env = XCURSOR_THEME,PlanaCursor
env = XCURSOR_SIZE,72
